// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CS_NMClient.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace IRPC
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface NMClient : Ice.Object, NMClientOperations_, NMClientOperationsNC_
    {
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public abstract class NMCommunicationRPCId
    {
        public const string value = "ID_NMCommunicationRPC";
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
    [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
    public partial interface NMServer : Ice.Object, NMServerOperations_, NMServerOperationsNC_
    {
    }
}

namespace IRPC
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public delegate void Callback_NMClient_SendData(int ret__);

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public delegate void Callback_NMServer_NMRegistClient();

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public delegate void Callback_NMServer_SendData(int ret__);
}

namespace IRPC
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface NMClientPrx : Ice.ObjectPrx
    {
        int SendData(string strXml);
        int SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<IRPC.Callback_NMClient_SendData> begin_SendData(string strXml);
        Ice.AsyncResult<IRPC.Callback_NMClient_SendData> begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_SendData(string strXml, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        int end_SendData(Ice.AsyncResult r__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface NMServerPrx : Ice.ObjectPrx
    {
        void NMRegistClient(string strClientId, IRPC.NMClientPrx Client);
        void NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<IRPC.Callback_NMServer_NMRegistClient> begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client);
        Ice.AsyncResult<IRPC.Callback_NMServer_NMRegistClient> begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        void end_NMRegistClient(Ice.AsyncResult r__);

        int SendData(string strXml);
        int SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> context__);

        Ice.AsyncResult<IRPC.Callback_NMServer_SendData> begin_SendData(string strXml);
        Ice.AsyncResult<IRPC.Callback_NMServer_SendData> begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__);

        Ice.AsyncResult begin_SendData(string strXml, Ice.AsyncCallback cb__, object cookie__);
        Ice.AsyncResult begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

        int end_SendData(Ice.AsyncResult r__);
    }
}

namespace IRPC
{
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface NMClientOperations_
    {
        int SendData(string strXml, Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface NMClientOperationsNC_
    {
        int SendData(string strXml);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface NMServerOperations_
    {
        void NMRegistClient(string strClientId, IRPC.NMClientPrx Client, Ice.Current current__);

        int SendData(string strXml, Ice.Current current__);
    }

    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public interface NMServerOperationsNC_
    {
        void NMRegistClient(string strClientId, IRPC.NMClientPrx Client);

        int SendData(string strXml);
    }
}

namespace IRPC
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public sealed class NMClientPrxHelper : Ice.ObjectPrxHelperBase, NMClientPrx
    {
        #region Synchronous operations

        public int SendData(string strXml)
        {
            return this.SendData(strXml, null, false);
        }

        public int SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            return this.SendData(strXml, context__, true);
        }

        private int SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            checkTwowayOnly__(__SendData_name);
            return end_SendData(begin_SendData(strXml, context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<IRPC.Callback_NMClient_SendData> begin_SendData(string strXml)
        {
            return begin_SendData(strXml, null, false, false, null, null);
        }

        public Ice.AsyncResult<IRPC.Callback_NMClient_SendData> begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_SendData(strXml, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_SendData(string strXml, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_SendData(strXml, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_SendData(strXml, ctx__, true, false, cb__, cookie__);
        }

        private const string __SendData_name = "SendData";

        public int end_SendData(Ice.AsyncResult r__)
        {
            IceInternal.OutgoingAsync outAsync__ = IceInternal.OutgoingAsync.check(r__, this, __SendData_name);
            try
            {
                if(!outAsync__.wait())
                {
                    try
                    {
                        outAsync__.throwUserException();
                    }
                    catch(Ice.UserException ex__)
                    {
                        throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                    }
                }
                int ret__;
                IceInternal.BasicStream is__ = outAsync__.startReadParams();
                ret__ = is__.readInt();
                outAsync__.endReadParams();
                return ret__;
            }
            finally
            {
                outAsync__.cacheMessageBuffers();
            }
        }

        private Ice.AsyncResult<IRPC.Callback_NMClient_SendData> begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            checkAsyncTwowayOnly__(__SendData_name);
            IceInternal.TwowayOutgoingAsync<IRPC.Callback_NMClient_SendData> result__ =  getTwowayOutgoingAsync<IRPC.Callback_NMClient_SendData>(__SendData_name, SendData_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__SendData_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeString(strXml);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void SendData_completed__(Ice.AsyncResult r__, IRPC.Callback_NMClient_SendData cb__, Ice.ExceptionCallback excb__)
        {
            int ret__;
            try
            {
                ret__ = end_SendData(r__);
            }
            catch(Ice.Exception ex__)
            {
                if(excb__ != null)
                {
                    excb__(ex__);
                }
                return;
            }
            if(cb__ != null)
            {
                cb__(ret__);
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static NMClientPrx checkedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            NMClientPrx r = b as NMClientPrx;
            if((r == null) && b.ice_isA(ice_staticId()))
            {
                NMClientPrxHelper h = new NMClientPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static NMClientPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            NMClientPrx r = b as NMClientPrx;
            if((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                NMClientPrxHelper h = new NMClientPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static NMClientPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId()))
                {
                    NMClientPrxHelper h = new NMClientPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static NMClientPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId(), ctx))
                {
                    NMClientPrxHelper h = new NMClientPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static NMClientPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            NMClientPrx r = b as NMClientPrx;
            if(r == null)
            {
                NMClientPrxHelper h = new NMClientPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static NMClientPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            NMClientPrxHelper h = new NMClientPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::IRPC::NMClient",
            "::Ice::Object"
        };

        public static string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, NMClientPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static NMClientPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if(proxy != null)
            {
                NMClientPrxHelper result = new NMClientPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public sealed class NMServerPrxHelper : Ice.ObjectPrxHelperBase, NMServerPrx
    {
        #region Synchronous operations

        public void NMRegistClient(string strClientId, IRPC.NMClientPrx Client)
        {
            this.NMRegistClient(strClientId, Client, null, false);
        }

        public void NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            this.NMRegistClient(strClientId, Client, context__, true);
        }

        private void NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            end_NMRegistClient(begin_NMRegistClient(strClientId, Client, context__, explicitCtx__, true, null, null));
        }

        public int SendData(string strXml)
        {
            return this.SendData(strXml, null, false);
        }

        public int SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> context__)
        {
            return this.SendData(strXml, context__, true);
        }

        private int SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitCtx__)
        {
            checkTwowayOnly__(__SendData_name);
            return end_SendData(begin_SendData(strXml, context__, explicitCtx__, true, null, null));
        }

        #endregion

        #region Asynchronous operations

        public Ice.AsyncResult<IRPC.Callback_NMServer_NMRegistClient> begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client)
        {
            return begin_NMRegistClient(strClientId, Client, null, false, false, null, null);
        }

        public Ice.AsyncResult<IRPC.Callback_NMServer_NMRegistClient> begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_NMRegistClient(strClientId, Client, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_NMRegistClient(strClientId, Client, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_NMRegistClient(strClientId, Client, ctx__, true, false, cb__, cookie__);
        }

        private const string __NMRegistClient_name = "NMRegistClient";

        public void end_NMRegistClient(Ice.AsyncResult r__)
        {
            end__(r__, __NMRegistClient_name);
        }

        private Ice.AsyncResult<IRPC.Callback_NMServer_NMRegistClient> begin_NMRegistClient(string strClientId, IRPC.NMClientPrx Client, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            IceInternal.OnewayOutgoingAsync<IRPC.Callback_NMServer_NMRegistClient> result__ = getOnewayOutgoingAsync<IRPC.Callback_NMServer_NMRegistClient>(__NMRegistClient_name, NMRegistClient_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__NMRegistClient_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeString(strClientId);
                IRPC.NMClientPrxHelper.write__(os__, Client);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void NMRegistClient_completed__(IRPC.Callback_NMServer_NMRegistClient cb__)
        {
            if(cb__ != null)
            {
                cb__();
            }
        }

        public Ice.AsyncResult<IRPC.Callback_NMServer_SendData> begin_SendData(string strXml)
        {
            return begin_SendData(strXml, null, false, false, null, null);
        }

        public Ice.AsyncResult<IRPC.Callback_NMServer_SendData> begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__)
        {
            return begin_SendData(strXml, ctx__, true, false, null, null);
        }

        public Ice.AsyncResult begin_SendData(string strXml, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_SendData(strXml, null, false, false, cb__, cookie__);
        }

        public Ice.AsyncResult begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
        {
            return begin_SendData(strXml, ctx__, true, false, cb__, cookie__);
        }

        private const string __SendData_name = "SendData";

        public int end_SendData(Ice.AsyncResult r__)
        {
            IceInternal.OutgoingAsync outAsync__ = IceInternal.OutgoingAsync.check(r__, this, __SendData_name);
            try
            {
                if(!outAsync__.wait())
                {
                    try
                    {
                        outAsync__.throwUserException();
                    }
                    catch(Ice.UserException ex__)
                    {
                        throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                    }
                }
                int ret__;
                IceInternal.BasicStream is__ = outAsync__.startReadParams();
                ret__ = is__.readInt();
                outAsync__.endReadParams();
                return ret__;
            }
            finally
            {
                outAsync__.cacheMessageBuffers();
            }
        }

        private Ice.AsyncResult<IRPC.Callback_NMServer_SendData> begin_SendData(string strXml, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, bool synchronous__, Ice.AsyncCallback cb__, object cookie__)
        {
            checkAsyncTwowayOnly__(__SendData_name);
            IceInternal.TwowayOutgoingAsync<IRPC.Callback_NMServer_SendData> result__ =  getTwowayOutgoingAsync<IRPC.Callback_NMServer_SendData>(__SendData_name, SendData_completed__, cookie__);
            if(cb__ != null)
            {
                result__.whenCompletedWithAsyncCallback(cb__);
            }
            try
            {
                result__.prepare(__SendData_name, Ice.OperationMode.Normal, ctx__, explicitContext__, synchronous__);
                IceInternal.BasicStream os__ = result__.startWriteParams(Ice.FormatType.DefaultFormat);
                os__.writeString(strXml);
                result__.endWriteParams();
                result__.invoke();
            }
            catch(Ice.Exception ex__)
            {
                result__.abort(ex__);
            }
            return result__;
        }

        private void SendData_completed__(Ice.AsyncResult r__, IRPC.Callback_NMServer_SendData cb__, Ice.ExceptionCallback excb__)
        {
            int ret__;
            try
            {
                ret__ = end_SendData(r__);
            }
            catch(Ice.Exception ex__)
            {
                if(excb__ != null)
                {
                    excb__(ex__);
                }
                return;
            }
            if(cb__ != null)
            {
                cb__(ret__);
            }
        }

        #endregion

        #region Checked and unchecked cast operations

        public static NMServerPrx checkedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            NMServerPrx r = b as NMServerPrx;
            if((r == null) && b.ice_isA(ice_staticId()))
            {
                NMServerPrxHelper h = new NMServerPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static NMServerPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            NMServerPrx r = b as NMServerPrx;
            if((r == null) && b.ice_isA(ice_staticId(), ctx))
            {
                NMServerPrxHelper h = new NMServerPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static NMServerPrx checkedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId()))
                {
                    NMServerPrxHelper h = new NMServerPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static NMServerPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            try
            {
                if(bb.ice_isA(ice_staticId(), ctx))
                {
                    NMServerPrxHelper h = new NMServerPrxHelper();
                    h.copyFrom__(bb);
                    return h;
                }
            }
            catch(Ice.FacetNotExistException)
            {
            }
            return null;
        }

        public static NMServerPrx uncheckedCast(Ice.ObjectPrx b)
        {
            if(b == null)
            {
                return null;
            }
            NMServerPrx r = b as NMServerPrx;
            if(r == null)
            {
                NMServerPrxHelper h = new NMServerPrxHelper();
                h.copyFrom__(b);
                r = h;
            }
            return r;
        }

        public static NMServerPrx uncheckedCast(Ice.ObjectPrx b, string f)
        {
            if(b == null)
            {
                return null;
            }
            Ice.ObjectPrx bb = b.ice_facet(f);
            NMServerPrxHelper h = new NMServerPrxHelper();
            h.copyFrom__(bb);
            return h;
        }

        public static readonly string[] ids__ =
        {
            "::IRPC::NMServer",
            "::Ice::Object"
        };

        public static string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Marshaling support

        public static void write__(IceInternal.BasicStream os__, NMServerPrx v__)
        {
            os__.writeProxy(v__);
        }

        public static NMServerPrx read__(IceInternal.BasicStream is__)
        {
            Ice.ObjectPrx proxy = is__.readProxy();
            if(proxy != null)
            {
                NMServerPrxHelper result = new NMServerPrxHelper();
                result.copyFrom__(proxy);
                return result;
            }
            return null;
        }

        #endregion
    }
}

namespace IRPC
{
    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public abstract class NMClientDisp_ : Ice.ObjectImpl, NMClient
    {
        #region Slice operations

        public int SendData(string strXml)
        {
            return SendData(strXml, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract int SendData(string strXml, Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ = 
        {
            "::IRPC::NMClient",
            "::Ice::Object"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[0];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[0];
        }

        public static new string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus SendData___(NMClient obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            string strXml;
            strXml = is__.readString();
            inS__.endReadParams();
            int ret__ = obj__.SendData(strXml, current__);
            IceInternal.BasicStream os__ = inS__.startWriteParams__(Ice.FormatType.DefaultFormat);
            os__.writeInt(ret__);
            inS__.endWriteParams__(true);
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "SendData",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if(pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch(pos)
            {
                case 0:
                {
                    return SendData___(this, inS__, current__);
                }
                case 1:
                {
                    return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                }
                case 2:
                {
                    return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                }
                case 3:
                {
                    return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                }
                case 4:
                {
                    return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }

    [_System.Runtime.InteropServices.ComVisible(false)]
    [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.6.1")]
    public abstract class NMServerDisp_ : Ice.ObjectImpl, NMServer
    {
        #region Slice operations

        public void NMRegistClient(string strClientId, IRPC.NMClientPrx Client)
        {
            NMRegistClient(strClientId, Client, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract void NMRegistClient(string strClientId, IRPC.NMClientPrx Client, Ice.Current current__);

        public int SendData(string strXml)
        {
            return SendData(strXml, Ice.ObjectImpl.defaultCurrent);
        }

        public abstract int SendData(string strXml, Ice.Current current__);

        #endregion

        #region Slice type-related members

        public static new readonly string[] ids__ = 
        {
            "::IRPC::NMServer",
            "::Ice::Object"
        };

        public override bool ice_isA(string s)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override bool ice_isA(string s, Ice.Current current__)
        {
            return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
        }

        public override string[] ice_ids()
        {
            return ids__;
        }

        public override string[] ice_ids(Ice.Current current__)
        {
            return ids__;
        }

        public override string ice_id()
        {
            return ids__[0];
        }

        public override string ice_id(Ice.Current current__)
        {
            return ids__[0];
        }

        public static new string ice_staticId()
        {
            return ids__[0];
        }

        #endregion

        #region Operation dispatch

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus NMRegistClient___(NMServer obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            string strClientId;
            IRPC.NMClientPrx Client;
            strClientId = is__.readString();
            Client = IRPC.NMClientPrxHelper.read__(is__);
            inS__.endReadParams();
            obj__.NMRegistClient(strClientId, Client, current__);
            inS__.writeEmptyParams__();
            return Ice.DispatchStatus.DispatchOK;
        }

        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static Ice.DispatchStatus SendData___(NMServer obj__, IceInternal.Incoming inS__, Ice.Current current__)
        {
            Ice.ObjectImpl.checkMode__(Ice.OperationMode.Normal, current__.mode);
            IceInternal.BasicStream is__ = inS__.startReadParams();
            string strXml;
            strXml = is__.readString();
            inS__.endReadParams();
            int ret__ = obj__.SendData(strXml, current__);
            IceInternal.BasicStream os__ = inS__.startWriteParams__(Ice.FormatType.DefaultFormat);
            os__.writeInt(ret__);
            inS__.endWriteParams__(true);
            return Ice.DispatchStatus.DispatchOK;
        }

        private static string[] all__ =
        {
            "NMRegistClient",
            "SendData",
            "ice_id",
            "ice_ids",
            "ice_isA",
            "ice_ping"
        };

        public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
        {
            int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
            if(pos < 0)
            {
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            switch(pos)
            {
                case 0:
                {
                    return NMRegistClient___(this, inS__, current__);
                }
                case 1:
                {
                    return SendData___(this, inS__, current__);
                }
                case 2:
                {
                    return Ice.ObjectImpl.ice_id___(this, inS__, current__);
                }
                case 3:
                {
                    return Ice.ObjectImpl.ice_ids___(this, inS__, current__);
                }
                case 4:
                {
                    return Ice.ObjectImpl.ice_isA___(this, inS__, current__);
                }
                case 5:
                {
                    return Ice.ObjectImpl.ice_ping___(this, inS__, current__);
                }
            }

            _System.Diagnostics.Debug.Assert(false);
            throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
        }

        #endregion

        #region Marshaling support

        protected override void writeImpl__(IceInternal.BasicStream os__)
        {
            os__.startWriteSlice(ice_staticId(), -1, true);
            os__.endWriteSlice();
        }

        protected override void readImpl__(IceInternal.BasicStream is__)
        {
            is__.startReadSlice();
            is__.endReadSlice();
        }

        #endregion
    }
}
